### PR TITLE
Fix env vars loading in Next.js

### LINKED ISSUE #171: Next.js not loading environment variables in browsers
## Steps to reproduce the problem
1. Make sure env variables are defined in `.env.local` or in the root of monorepo in `.env`
2. Run `saleor-app-checkout` on main brach with `pnpm run dev`
3. Visit the app at `localhost:3000`

## Current result
`NEXT_PUBLIC_SALEOR_API_URL` is not exposed to the client: `undefined` in browser, OK in node.

## Expected behavior
`NEXT_PUBLIC_*` variables are loaded correctly in browsers

### System:
 - OS: macOS 12.4
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 174.21 MB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
### Binaries:
 - Node: 18.2.0 - /usr/local/bin/node
 - Yarn: 1.22.18 - /usr/local/bin/yarn
 - npm: 8.9.0 - /usr/local/bin/npm
 - Watchman: 2022.05.16.00 - /usr/local/bin/watchman
 - pnpm: 7.5.2
### Browsers:
 - Brave Browser: 103.1.40.113
 - Chrome: 103.0.5060.134
 - Firefox Developer Edition: 101.0
 - Safari: 15.5

### PR DESCRIPTION
**Pull request by witoszekdev**
This fixes saleor/saleor-checkout#171 - env vars not loading in `saleor-app-checkout`

### CODE REVIEW

**Comment by witoszekdev** [comment]
@mmiszy We probably should use `env-vars` pacakge to load environment variables in every script.

It would look like `env-cmd` except work automatically wherever the script is run (root of monorepo or the package directory):

```json
// apps/saleor-app-checkout/package.json
"dev": "env-vars next dev"
```

```json
// package.json
"dev": "env-vars turbo run dev"
```

Our current guide for deploying checkout to Vercel says that the env vars will be loaded from `.env` file in the root of monorepo, which just doesn't work with our current setup :/

**Comment by bmigirl** [comment]
So: 
- pulled the changes 
- set the app url in env local to localhost:3001
- run `pnpm dev --filter=saleor-app-checkout...` in root
- localhost:3001 checkout spa with checkout works fine 
- customization settings api throws 500

When entered e.g http://localhost:3001/api/active-payment-providers/Q2hhbm5lbDoyMjQz got this error:
`Invariant Violation: TEST_MOLLIE_KEY is not defined`

**Comment by witoszekdev** [comment]
> So:
> 
> * pulled the changes
> * set the app url in env local to localhost:3001
> * run `pnpm dev --filter=saleor-app-checkout...` in root
> * localhost:3001 checkout spa with checkout works fine
> * customization settings api throws 500
> 
> When entered e.g http://localhost:3001/api/active-payment-providers/Q2hhbm5lbDoyMjQz got this error: `Invariant Violation: TEST_MOLLIE_KEY is not defined`

@bmigirl it's handled in another PR: https://github.com/saleor/saleor-checkout/pull/189

**Comment by mmiszy** [comment]
Please open the PR again in https://github.com/saleor/react-storefront

**Pull request closed without merging**
