### PR TITLE
UI Kit module bundler swap

### PR DESCRIPTION
**Pull request by adrian-potepa**
In this PR I want to swap module bundler tsup to rollup.

### CODE REVIEW

**Review by bmigirl — APPROVED** [review]

**Review by jwm0 — APPROVED** [review]

**Comment by krzysztofwolski** [comment]
@bmigirl Was there any issues on your machine when building the ui-kit? I'm getting

```
❯ pnpm build 

> @saleor/ui-kit@0.0.0 build saleor-checkout/packages/ui-kit
> rollup -c


src/index.ts → dist/cjs/index.js, dist/esm/index.js...
(!) Plugin typescript: @rollup/plugin-typescript TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
src/components/Text/Text.tsx: (19:6)

19   ...rest
        ~~~~

created dist/cjs/index.js, dist/esm/index.js in 6.9s

dist/esm/types/index.d.ts → dist/index.d.ts...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@lib/globalTypes (imported by dist/esm/types/components/Chip/Chip.d.ts, dist/esm/types/components/Checkbox/Checkbox.d.ts, dist/esm/types/components/IconButton/IconButton.d.ts, dist/esm/types/components/InfoTip/InfoTip.d.ts, dist/esm/types/components/Radio/Radio.d.ts, dist/esm/types/components/Select/Select.d.ts, dist/esm/types/components/Switch/Switch.d.ts)
created dist/index.d.ts in 133ms
```

**Comment by bmigirl** [comment]
@krzysztofwolski found (this issue)[https://github.com/ezolenko/rollup-plugin-typescript2/issues/231] - so as mentioned in the latest comment, added tslib manually. Also fixed wrong name of Radio component because its import failed as well. I think it works now, can you confirm?

**Comment by krzysztofwolski** [comment]
@bmigirl installed and was able to run build. I'm only getting warnings about unresolved dependencies:
```
❯ pnpm build              

> @saleor/ui-kit@0.0.0 build saleor-checkout/packages/ui-kit
> rollup -c


src/index.ts → dist/cjs/index.js, dist/esm/index.js...
created dist/cjs/index.js, dist/esm/index.js in 7.1s

dist/esm/types/index.d.ts → dist/index.d.ts...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@lib/globalTypes (imported by dist/esm/types/components/Checkbox/Checkbox.d.ts, dist/esm/types/components/Chip/Chip.d.ts, dist/esm/types/components/IconButton/IconButton.d.ts, dist/esm/types/components/InfoTip/InfoTip.d.ts, dist/esm/types/components/Radio/Radio.d.ts, dist/esm/types/components/Select/Select.d.ts, dist/esm/types/components/Switch/Switch.d.ts)
created dist/index.d.ts in 166ms
```

**Comment by bmigirl** [comment]
Added export of lib from ui ki, it works in checkout but warning is still present at build. Since this pr is a blocker added a ticket, for now leaving the warning as it is

**Pull request merged**
